### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [cyberboysumanjay/JioSaavnAPI#24]
https://jiosaavn.ga/api/?query=bole+jo+koyal

**Comment by cyberboysumanjay** [comment]
Hey @ParveenBhadooOfficial , 
Thanks for reporting this issue.

Some songs having incomplete metadata was causing this crash.
It should be fixed by this commit https://github.com/cyberboysumanjay/JioSaavnAPI/commit/9e45b0e3b6eb5b46c82263837fbfa00c8f29f7ef

Feel free to reopen this issue in case the issue still persists.

**Comment by ParveenBhadooOfficial** [comment]
http://15.207.9.188/result/?query=bole+jo+koyal

Issue still persists.

**Comment by cyberboysumanjay** [comment]
I missed one more thing 😕 
Probably https://github.com/cyberboysumanjay/JioSaavnAPI/commit/b10dd22bd753a12f1f6cd1cb408fac5ec42ad23b should fix it.
Redeploy the latest build and let me know if it works fine or not.

**Comment by ParveenBhadooOfficial** [comment]
Fixed. Working Fine. Test at http://15.207.9.188/result/?query=bole+jo+koyal

Thank You.
